name: folding  # Replace with your environment name
channels:
  - defaults
  - conda-forge  # Add other channels if needed
dependencies:
  - python=3.9  # Specify the Python version
  - openmm=8.1.2
  - pandas=2.2.2
  - pytorch=2.3.0  # torch is often installed as pytorch via conda
  - loguru=0.7.0
  - pip=24.2
  - pdbfixer=1.9
  - gzip==1.13
  - pip:
      - bittensor==6.9.4
      - tenacity==9.0.0
      - python-dotenv==1.0.1
      - wandb==0.17.2
      - eth-utils==2.1.1
      - numpy==1.26.4
      - parmed==4.2.2
      - plotly==5.22.0
      - kaleido==0.2.1
      - async-timeout==4.0.3